model_name:
  - dual_patch


detector_path:

  - ./training/config/detector/dualbranchpatch.yaml


test_dataset:
  - "FaceForensics++"
  - "DFDCP"
  - "Celeb-DF-v2"
  - "DFDC"
  - "DeepFakeDetection"

weights_path:
  - /home/jeyoung/DeepfakeBench/logs/training/dual_branch_patch_2026-07-07-08-37-20/test/avg/ckpt_best.pth

gpu:
  - 5
  # - 1