model_name:
  # - clip_simple_lora_dfdcp
  # - dino_lora_dfdcp
  # - spsl_dfdcp
  # - recce_dfdcp
  - dual_vic_sr


detector_path:
  # - ./training/config/detector/clip_simple_lora.yaml
  # - ./training/config/detector/dino_lora.yaml
  # - ./training/config/detector/spsl.yaml
  # - ./training/config/detector/recce_dfdcp.yaml
  # - ./training/config/detector/dual_branch.yaml
  # - ./training/config/detector/dual_branch.yaml
  # - ./training/config/detector/dual_branch.yaml
  - ./training/config/detector/dual_branch.yaml


test_dataset:
  - "FaceForensics++"
  - "DFDCP"
  - "Celeb-DF-v2"
  - "DFDC"
  - "DeepFakeDetection"

weights_path:

  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/clip_lora_dfdcp_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/dino_lora_dfdcp_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/spsl_dfdcp_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/recce_dfdcp_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/dual_branch_vicregweight_0001_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/dual_branch_nu5_ckpt_best.pth   
  # - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/dual_branch_nu10_ckpt_best.pth   
  - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/dual_vic_sr_ckpt_best.pth  


gpu:
  - 2
  # - 1