model_name:
  - xception
  - srm
  - recce
  - efficientnetb4


detector_path:
  - ./training/config/detector/xception.yaml
  - ./training/config/detector/srm.yaml
  - ./training/config/detector/recce.yaml
  - ./training/config/detector/efficientnetb4.yaml


test_dataset:
  - "FaceForensics++"
  - "DFDCP"
  - "Celeb-DF-v2"
  - "DFDC"
  - "DeepFakeDetection"

weights_path:
  - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/xception_ckpt_best.pth
  - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/srm_ckpt_best.pth
  - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/recce_ckpt_best.pth
  - /media/NAS/USERS/jeyoung/checkpoints/FF_trained/efficientnet_ckpt_best.pth


gpu:
  - 0
  # - 1